<?php
echo "SERVER_NAME=".$_SERVER['SERVER_NAME']."<BR>";
echo "DOCUMENT_ROOT=".$_SERVER['DOCUMENT_ROOT']."<BR>";
echo "SCRIPT_FILENAME=".$_SERVER['SCRIPT_FILENAME']."<BR>";
echo "SCRIPT_NAME=".$_SERVER['SCRIPT_NAME']."<BR>";
echo "REQUEST_URI=".$_SERVER['REQUEST_URI']."<BR>";
echo "PHP_SELF=".$_SERVER['PHP_SELF']."<BR>";
?>
